### ISSUE TITLE
Complete CRAN release checklist

### ISSUE THREAD

**Issue by shntnu** [shntnu/pertminr#64]
http://r-pkgs.had.co.nz/release.html

- [x] Update README.md
- [x] Update NEWS.md
- [x] Figure out what the version should be and update DESCRIPTION and NEWS.md
